### ISSUE TITLE
Multiple voting

### ISSUE THREAD

**Issue by PraveshMoelchand** [emieldesmidt/kotlin-ipv8#3]
It is currently possible to cast multiple votes on the same proposal.
You can reply multiple times on a proposal and the response is recorded in the chain. In addition, it is possible to reply on your own vote!

**Comment by PraveshMoelchand** [comment]
We tried to check whether a block has already been signed, but we were not able to find the difference between a signed and unsigned block in the chain. We already tried the following:

- Looking for the difference between the signature of signed and unsigned block, but we could not find a pattern or difference
- Using the empty signature for differentiating signed and unsigned blocks, but even the signature of an unsigned block was not equal to the empty signature, we used the following code:
```
fun createVoteAgreementBlock(link: TrustChainBlock, transaction: TrustChainTransaction) {
        Log.e("vote_debug", link.signature.toString(Charsets.UTF_8))
        Log.e("vote_debug", EMPTY_SIG.toString(Charsets.UTF_8))
        trustChainCommunity.createAgreementBlock(link, transaction)
    }
```
This yielded the following output:
```
2020-03-17 15:11:12.074 11603-11603/nl.tudelft.ipv8.android.voting E/vote_debug: [B@a4e92e0
2020-03-17 15:11:12.074 11603-11603/nl.tudelft.ipv8.android.voting E/vote_debug: [B@d74f999
```

**Comment by erwinvanthiel** [comment]
We (@erwinvanthiel @PraveshMoelchand) tried to check whether a participant has already voted by listing the keys of the voteres, but the key of the signer appears to change at everysigning. We already tried the following: 

`if (voters.contains(it.linkPublicKey.toString())){
                continue
}`

`
"YES" -> {
                    yesCount++
                    voters.add(it.linkPublicKey.toString())
                    Log.e("vote_debug", it.linkPublicKey.toString())
                }

`
